import type { Metadata } from 'next'
import { yekan } from '@/utils/fonts'
import './globals.css'
import Layout from '@/layout/Layout'

export const metadata: Metadata = {
  title: 'Flight Ticket',
  description: 'Generated by Reza Aminizadeh',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={yekan.className}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
